### ISSUE TITLE
How to make compatible in iPhone 6 and latter.

### ISSUE THREAD

**Issue by Mitesh-Mewada** [daisukenagata/RecordARFace#3]
Hey @daisukenagata i check your library when i run in iPhone 7 and 6s its run but can't open camera and recorded face base AR how to solve this .

i want to **develop in all iPhone 6 and latter**, it is possible ?

**Comment by DaisukeNagata** [comment]
Hey @Mitesh-Mewada  

There is an answer in the reference.

////////////////////////////////////////////////////////////////////////////////////////////////////////////
https://developer.apple.com/documentation/arkit/arfacetrackingconfiguration

Face tracking is available only on iOS devices with a front-facing TrueDepth camera (see iOS Device Compatibility Reference). Use the ARFaceTrackingConfiguration isSupported property to determine whether face tracking is available on the current device before offering the user any features that require face tracking.
////////////////////////////////////////////////////////////////////////////////////////////////////////////

Thank you for the question!
